-- Attributed sessions, as a view, so the reminder rules and the Coach Players
-- page can't drift apart on who coached what. Attribution matches what those
-- pages already do: the assigned coach wins, then a "Coach Simon/Simpson"
-- title, otherwise David. The slug list is spelled out rather than read from
-- crm_staff so a new staff row can't silently change existing attribution.
CREATE OR REPLACE VIEW coach_player_sessions AS
SELECT
  'regular'::text AS source,
  s.id            AS session_id,
  CASE
    WHEN st.slug IN ('david','simon','simpson','girish','george','tyrone') THEN st.slug
    WHEN lower(btrim(s.title)) LIKE 'coach simpson%' THEN 'simpson'
    WHEN lower(btrim(s.title)) LIKE 'coach simon%'   THEN 'simon'
    ELSE 'david'
  END             AS coach_slug,
  pl.id           AS crm_player_id,
  s.session_date,
  s.package_id
FROM crm_sessions s
LEFT JOIN crm_staff st ON st.id = s.coach_id
JOIN crm_session_players sp ON sp.session_id = s.id
JOIN crm_players pl ON pl.id = sp.player_id
WHERE s.cancelled IS NOT TRUE
UNION ALL
SELECT
  'first'::text,
  s.id,
  CASE
    WHEN st.slug IN ('david','simon','simpson','girish','george','tyrone') THEN st.slug
    WHEN lower(btrim(s.title)) LIKE 'coach simpson%' THEN 'simpson'
    WHEN lower(btrim(s.title)) LIKE 'coach simon%'   THEN 'simon'
    ELSE 'david'
  END,
  pl.id,
  s.session_date,
  NULL::integer
FROM crm_first_sessions s
LEFT JOIN crm_staff st ON st.id = s.coach_id
JOIN crm_first_session_players fsp ON fsp.first_session_id = s.id
JOIN crm_players pl ON pl.id = fsp.player_id
WHERE s.cancelled IS NOT TRUE;

-- Reminders are generated by the hourly cron, never by hand. `anchor` names the
-- thing that triggered the reminder (a session, a package, a session-count
-- milestone, a date), and the unique constraint on it is what makes the cron
-- idempotent: re-running never duplicates an open reminder.
--
-- Report reminders close themselves once the report exists. Parent check-ins
-- and photo/video prompts happen off-platform, so they close via the Done
-- button, and `done_at` on the last check-in is what starts the next 2 weeks.
CREATE TABLE coach_reminders (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  coach_slug    TEXT NOT NULL,
  crm_player_id INTEGER NOT NULL REFERENCES crm_players(id) ON DELETE CASCADE,
  kind          TEXT NOT NULL CHECK (kind IN (
                  'mini_note', 'initial_report', 'progress_report',
                  'parent_checkin', 'media'
                )),
  anchor        TEXT NOT NULL,
  anchor_date   DATE NOT NULL,
  status        TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
  done_at       TIMESTAMPTZ,
  done_by       UUID REFERENCES parents(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (kind, crm_player_id, anchor)
);

CREATE INDEX ON coach_reminders(coach_slug, status, anchor_date DESC);
CREATE INDEX ON coach_reminders(crm_player_id, kind, status);

CREATE TRIGGER coach_reminders_set_updated_at BEFORE UPDATE ON coach_reminders
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
